INFO:root:display_info ran for 1.0011494159698486 secs with args: John and kwargs: 29
ERROR:root:Traceback (most recent call last):
  File "/home/peter/PycharmProjects/LearnPythonRepo/My-Wrapper.py", line 16, in wrapper
    result = original_function(*args, **kwargs)
TypeError: display_info() takes 2 positional arguments but 3 were given

INFO:root:[03/03/2019, 21:58:32] display_info ran for 1.0011866092681885 secs with args: John and kwargs: 29
ERROR:root:Traceback (most recent call last):
  File "/home/peter/PycharmProjects/LearnPythonRepo/My-Wrapper.py", line 16, in wrapper
    result = original_function(*args, **kwargs)
TypeError: display_info() takes 2 positional arguments but 3 were given

ERROR:root:Traceback (most recent call last):
  File "/home/peter/PycharmProjects/LearnPythonRepo/My-Wrapper.py", line 16, in wrapper
    result = original_function(*args, **kwargs)
TypeError: display_info() takes 2 positional arguments but 3 were given

INFO:root:[03/03/2019, 22:11:01] display_info ran for 1.0011720657348633 secs with args: John and kwargs: 29
ERROR:root:03/03/2019, 22:11:05Traceback (most recent call last):
  File "/home/peter/PycharmProjects/LearnPythonRepo/My-Wrapper.py", line 16, in wrapper
    result = original_function(*args, **kwargs)
TypeError: display_info() takes 2 positional arguments but 3 were given

ERROR:root:03/03/2019, 22:11:27 Traceback (most recent call last):
  File "/home/peter/PycharmProjects/LearnPythonRepo/My-Wrapper.py", line 16, in wrapper
    result = original_function(*args, **kwargs)
TypeError: display_info() takes 2 positional arguments but 3 were given

